language: node_js
node_js:
- lts/*
before_script:
- npm ci
- npm run build
script:
- npm run lint
- npm run test
after_success: 
deploy:
  provider: npm
  email: dev@marvingaube.de
  api_key:
    secure: E2ChD0GM/vmsC1ntFMI7wosY9Iuon0aITOKfGC29Q3ChaH4+bkwK/G7AW+zPOMIUxP11OiqZL+u7WiZGRdOkB6BudVgRf7ntRCgKPyL/9k9MDCb+f+i/omFbMhePd8Rp/794w8qTA34IkOkHKuOOCASXrFXn4QxhasyiNMcK2Eo++Y1L20tc0VtwZypJDiz78Alh0wciYK7K4w8IvDUFIwxJGlyw8SKC7JadYK4foFYHGXkqaUIvRdhLbHT0F+CDdjbcmJAWph4OSCxwQeKgWqNRR5ZPLDlc83IPoQ1zmwb+JwBeACneDpYXui7qwwYDEYzy8V60eaLFUmWYPeKhpHlDr9LGE//t5VuMs2dtliFSyP3P2FXFJHyW/4Hl0S/J92dTwaeoLuiPvShd/7XgPDvxzPC1zCuXy5Njv0jYzUpBvemjfz97GT7yCrHoIrwV2erdeTl2eOGH4kVuCwloq5v2loN+94MzxTtMmgVYUjFCGz1LapUbYgXX7FxtHOBcSwJe+R3WoYFsONV9IPvQQOzqCqcu02yMxPrHY9yF/zb49f3HiyNYvZivad2ds/FtT60SbKTOCAjttamvTX8dHWUnHJK0FaoNJ38I1+rODTlYMLT6ClRb0QoV/Dc6teC/IyXQuGzrb8AqXRwPR/ek8b7sqFhwv+vUZ002QOQcEXM=
  on:
    tags: true
    repo: ShowComposer/datalib
