language: node_js
node_js:
- lts/*
before_script:
- npm ci
- npm run build
script:
- npm run lint
- npm run test
after_success: 
deploy:
  provider: npm
  email: dev@marvingaube.de
  api_key:
    secure: CiqjMXSFM7HLWRnqpnpBiueiVW3vVg2HnCP8xSOfwZEc+pSKOwADR69+qETIpltG4bhenyD8JTg/M0PBljkiyCmU5bH6zZYVOn5uMH4RenSyVBTjG8yKl/Zq+yarMdMmyMjdf10ugEAb/bV3tSJwGGATkc0Fc14fRG33CCrTlu4NZXDQCd0ooHytOH+nasEoysIlSmsnp1UU4ua7YSmDRKZXTfVTcc+yVcVJ4gL1KNPy3QDjAQP/7XDK15UXzB3uQrDW/Kd6/ZpTKcw+KnmcmlSc/dGDJtRkEyU9Rep5m2brcD8BvB1n9aGrUlIMev2yqVRJh/eGGN+Hei60TQYb5v+Fg0XhlGhEoBVUwzhd+qti+j/uqyqkLFCovK0sflFPLfJn6O4THKPpoLwEwUYdgjIADFCbJvKaypl7pLdEU1KueJc8p9lwGhrBo//H/cYckeBZ6Sr8afR5KZkl5Id9kK01XoGL3qAAQUqFEq1EbkX4EKta4nU1rru3flhhuOQe28sZFUWSekriXjhZOlcdLv7E4D/DXlmZ0QEjlcxZSUOFU3EFSiH7YQPOzTFC2ol52hM4bqkq9NPI8qWFiWxxznidx252TO2YL5CvGoNraD07eR4Aa5fRehu85v4SsHKxd1kj+szu/w0/7gBMf1oOqIZ6q4bhhWzejk4vRHTfkXc=
  on:
    tags: true
    repo: ShowComposer/datalib
