language: node_js
node_js:
- lts/*
before_script:
- npm ci
- npm run build
script:
- npm run lint
- npm run test
after_success: 
deploy:
  provider: npm
  email: dev@marvingaube.de
  api_key:
    secure: b4WK8bGOYFKaGnJgisFhq/7JePANsU4mY3FUzQTCUrhCu1WZWXMCz8C2vMu3Ya6RD5lFLXGGDmzIvJSZ8nAbL7V83BEm2AQHdxDFlCJ+mev3a9q5QFZzxaH3QAyeWQhcD75AiVEIuiX+/15XSDNNQHlemMhR4kPyU8ZvTseQbDuLN6MJ406v+GAD6NrGNY+99+er+0d84rVII0JO5G0ZKN3EFeupWmvjBC7i6KAw7wIdnIMZElcD+QehbYdwoKPs6/3OHTJjLMFk0zz7qgKFdsokxbhPyGcBD3jScz/e+yo+Wg01CrG2l9nivbhgNJ0663et/4I87AFWpo6gKifdVKqzn9ZlPhJmtkTxKsq0Q6vR8TlCA2aAwS8WouShAwBfLJJm7mcEsuKV3lbkmI4czfHpICU8OnxJWf8FLE7AU2XBpUBxvNarhznDcaSPc5gcS2EMLqUSds6zb9FRJtSiu2qALFhVLm4Xi8aumjX2/XecTSneEC5DPPewvqf2NOW/JaU9rIa6vN7x2dEdXjbdcXfQ57Y7MT2thejSZDZKAUo8+vKSvwf/SaTWmPTP745wJbhnfBmcOgQZS2Z5rgLBCxgbFJ9rUrvWI3YryWxhZnDKxkY+nFcArubwfkxevJbCkLxUmcdmVfxvK0o9gndgWZdqP5zJerxoO3Z6H9LG2sE=
  on:
    tags: true
    repo: ShowComposer/datalib
